version: '3'

services:

  db:
    container_name: scalabledb
    image: postgres
    hostname: db
    environment:
      GET_HOST_FROM: dns
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    networks:
      - scalablenet

  scalableapi:
    container_name: scalableapi
    image: kisulken/scalableapi:v1
    hostname: scalableapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GET_HOSTS_FROM: dns
    networks:
      - scalablenet
    volumes:
      - .:/go/src/scalableApi
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    labels:
      kompose.service.type: LoadBalancer

networks:
  bulletinnet:
    driver: bridge